name: run unit tests
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - 'develop'
  #    - 'main'
  pull_request:
    types: [opened, reopened]
    branches:
      - 'develop'
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ping e14
        run: |
          wget http://element14.com
          cat index.html
